baseURL: https://dinoslow.github.io/
languageCode: en-us
title: WINSTON WANG
theme: PaperMod
params:
  # Theme
  defaultTheme: auto

  # Profile
  profileMode:
    enabled: false
    title: "WELCOME"
    buttons:
      - name: "ABOUT ME"

  # Home Information
  homeInfoParams:
    Title: Hi! I'm Winston 👋
    ImageURL: "./images/profile.png"
    Content: "CS @ National Tsing Hua University | Ex-RA in Diffusion Model @ <a href='https://www.sinica.edu.tw/en/Tab/4' target='_blank'>Academia Sinica</a>"
    Description:
      - point: "<strong>Phi Tau Phi Scholastic Honor Society</strong> Member <strong> (Top 1%) </strong>"
      - point: "<strong>First Prize</strong> of Graduation Project Competition, NTHU CS <strong> (Top 1%) </strong>"
      - point: "<strong>Vice President</strong>, NTHU CS Student Association (2021 - 2022)"

  # Social Links
  socialIcons:
    - name: Email
      url: "mailto:winston0724@gmail.com"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/winston-wang-587843240/"
    - name: GitHub
      url: "https://github.com/dinoslow"

  # Special Information
  specialInfoParams:
    enabled: true
    Title: "What's poppin? 🔥"
    Posts:
      - specialTitle: "Our Paper is Accepted by WACV 2025!"
        specialContent: "DiffQRCoder: Diffusion-based Aesthetic QR Code Generation with Scanning Robustness Guided Iterative Refinement - Jia-Wei Liao, Winston Wang*, Tzu-Sian Wang*, Li-Xuan Peng*, Ju-Hsuan Weng, Cheng-Fu Chou, Jun-Cheng Chen"
        link: "https://jwliao1209.github.io/DiffQRCoder/"
      - specialTitle: "Introducing --- \"Buggy\"!"
        specialContent: "Buggy, a chrome extension that helps user to organize website they find useful yet not disrupting the development workflow."
        link: "https://chromewebstore.google.com/detail/buggy-save-organize-and-s/djenljcggbjleffdeejenepeiialldci"

  # Education Information
  educationInfoParams:
    enabled: true
    Title: "Education 🎓"
    Schools:
      - schoolName: "National Tsing Hua University"
        degree: "B.S., Computer Science"
        duration: "Sep. 2020 - Jan. 2024 (Graduated Early)"
        imageUrl: "./images/tsinghua.png"
  
  # Experience Information
  experienceInfoParams:
    enabled: true
    Title: "Experience 💼"
    Experiences:
      - companyName: "ROC Army"
        position: "Compulsory Military Service"
        duration: "Apr. 2024 - Aug. 2024"
        imageUrl: "./images/military.png"
        additionalUrl: "https://www.ait.org.tw/military-service-in-taiwan/"
      - companyName: "Academia Sinica"
        position: "Part-time Research Assistant (Diffusion Model)"
        duration: "Sep. 2023 - Mar. 2024"
        imageUrl: "./images/sinica.png"
      - companyName: "Academia Sinica"
        position: "Research Intern (Diffusion Model)"
        duration: "Jul. 2023 - Sep. 2023"
        imageUrl: "./images/sinica.png"
      - companyName: "National Tsing Hua University"
        position: "Teaching Assistant of Software Studio (Teaching React, JavaScript)"
        duration: "Jan. 2023 - Jun. 2023"
        imageUrl: "./images/tsinghua.png"
      - companyName: "Galaxy Software Services Corporation"
        position: "Full Stack Developer Intern"
        duration: "Jul. 2022 - Jan. 2023"
        imageUrl: "./images/gss.jpg"


# Menu
menu:
  main:
    - name: RESUME
      url: "https://drive.google.com/file/d/1dERcCcUDm2lZhCCTUKVzLrPSoTNsL3cW/view?usp=sharing"
  